apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ include "chart.fullname" . }}-web
  labels:
    app: {{ include "chart.fullname" . }}-web

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chart.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "chart.fullname" . }}-web
    spec:
      restartPolicy: {{ .Values.restartPolicy }} 
      containers:
        - name: django-img 
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}

