version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;
      python manage.py makemigrations &&
      python manage.py migrate &&
      echo "from django.contrib.auth.models import User; User.objects.create_superuser(username=\"admin\", password=\"secret\", email=\"admin@example.com\")" | python manage.py shell &&
      python manage.py runserver'
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=django_db
    ports:
      - 5432:5432

volumes:
  postgres_data: