version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - 8000:8000
    restart: always
    links:
      - db
    networks:
      - pynetwork


  db:
    image: postgres
    # container_name: psqldb 
    volumes:
      - /home/mahin/dev/github.com/opsThing/database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=django_db
    ports:
      - 5432:5432
    networks:
      - pynetwork

networks:
  pynetwork:
    driver: bridge