# General settings
deployment:
  replicas: 1
  annotations:
  # Add any annotations you want to set for the Traefik deployment

# Service settings
service:
  annotations:
    test1: test1
  # Add any annotations you want to set for the Traefik service
  ports:
    web:
      nodePort: 30122

# Ingress settings
ingressRoute:
  enabled: true
  additionalMiddlewares:
  # Add any additional middlewares you want to apply to the routes
  routes:
  - kind: IngressRoute
    name: app-django-app-web-ing
    namespace: default
    spec:
      entryPoints:
      - web
      routes:
      - kind: Rule
        match: Host(`dummy.localhost`)
        services:
        - name: app-django-app-web-svc
          port: 8000

dashboard:
  enabled: true
